// <auto-generated />
using System;
using Globomantics.Survey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Globomantics.Survey.Migrations.GlobomanticsSurveyDb
{
    [DbContext(typeof(GlobomanticsSurveyDbContext))]
    partial class GlobomanticsSurveyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Globomantics.Survey.Areas.Identity.Data.GloboSurveyUserTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GloboSurveyUserTickets");

                    b.HasData(
                        new
                        {
                            Id = "7d186beb-99c7-45e3-bb6e-fc07954d03a4",
                            Message = "I've recently changed my surname from May to Johnson, could you update your system please?",
                            Title = "Name change required",
                            UserId = "8f8afc29-228d-4508-9f7a-7d17c4ae9901"
                        });
                });

            modelBuilder.Entity("Globomantics.Survey.Models.CustomerSurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedEmailDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SurveyCompleteMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomerSurveys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900"),
                            ExpectedEmailDomain = "globomantics.com",
                            IsRange = false,
                            SurveyCompleteMessage = "You completed the survey, THANKS!!!",
                            Title = "Staff Survey - Carved Rock"
                        },
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9000"),
                            ExpectedEmailDomain = "globomantics.com",
                            IsRange = true,
                            SurveyCompleteMessage = "You completed the survey, THANKS!!!",
                            Title = "Range Survey - Carved Rock"
                        });
                });

            modelBuilder.Entity("Globomantics.Survey.Models.CustomerSurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomerSurveyResponses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc0a488f-25b0-4756-b4fc-2ead62896f1a"),
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        },
                        new
                        {
                            Id = new Guid("bef44a27-4c67-4532-9746-89b9f52a3ef2"),
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        });
                });

            modelBuilder.Entity("Globomantics.Survey.Models.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("SurveyAnswer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd8e213c-df86-4996-9088-4af913a56b16"),
                            Answer = "Less than 1 year",
                            Question = "How long have you worked at Carved Rock?",
                            SurveyResponseId = new Guid("cc0a488f-25b0-4756-b4fc-2ead62896f1a")
                        },
                        new
                        {
                            Id = new Guid("b38f99b9-1dbc-4358-b7df-d17e05f7cc93"),
                            Answer = "Yes",
                            Question = "Do you enjoy working at Carved Rock?",
                            SurveyResponseId = new Guid("cc0a488f-25b0-4756-b4fc-2ead62896f1a")
                        },
                        new
                        {
                            Id = new Guid("8f878cf3-2723-4cee-b6e3-1b2e4f75bcce"),
                            Answer = "It's really cool here!",
                            Question = "Any comments on how you find working for Carved Rock?",
                            SurveyResponseId = new Guid("cc0a488f-25b0-4756-b4fc-2ead62896f1a")
                        },
                        new
                        {
                            Id = new Guid("c995f2f0-e47e-46e4-90e5-53637bf348b9"),
                            Answer = "More than 5 years",
                            Question = "How long have you worked at Carved Rock?",
                            SurveyResponseId = new Guid("bef44a27-4c67-4532-9746-89b9f52a3ef2")
                        },
                        new
                        {
                            Id = new Guid("8d188615-e253-4db6-b97b-1bea3d03b112"),
                            Answer = "No",
                            Question = "Do you enjoy working at Carved Rock?",
                            SurveyResponseId = new Guid("bef44a27-4c67-4532-9746-89b9f52a3ef2")
                        },
                        new
                        {
                            Id = new Guid("3cb59ff2-11e2-4c95-8345-a0e759b72ac5"),
                            Answer = "My computer is really slow",
                            Question = "Any comments on how you find working for Carved Rock?",
                            SurveyResponseId = new Guid("bef44a27-4c67-4532-9746-89b9f52a3ef2")
                        });
                });

            modelBuilder.Entity("Globomantics.Survey.Models.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PossibleAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("CustomerSurveyQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9901"),
                            Answer = "",
                            PossibleAnswers = "Less than 1 year|1-5 years|More than 5 years",
                            Question = "How long have you worked at Carved Rock?",
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        },
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9902"),
                            Answer = "",
                            PossibleAnswers = "Yes|No|Sometimes",
                            Question = "Do you enjoy working at Carved Rock?",
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        },
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9904"),
                            Answer = "",
                            PossibleAnswers = "",
                            Question = "Any comments on how you find working for Carved Rock?",
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9900")
                        },
                        new
                        {
                            Id = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9001"),
                            Answer = "",
                            PossibleAnswers = "",
                            Question = "Rate us bad - good",
                            SurveyId = new Guid("8f8afc29-228d-4508-9f7a-7d17c4ae9000")
                        });
                });

            modelBuilder.Entity("Globomantics.Survey.Models.SurveyAnswer", b =>
                {
                    b.HasOne("Globomantics.Survey.Models.CustomerSurveyResponse", "SurveyResponse")
                        .WithMany("Answers")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyResponse");
                });

            modelBuilder.Entity("Globomantics.Survey.Models.SurveyQuestion", b =>
                {
                    b.HasOne("Globomantics.Survey.Models.CustomerSurvey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Globomantics.Survey.Models.CustomerSurvey", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Globomantics.Survey.Models.CustomerSurveyResponse", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
